### PR TITLE
Added option for named json objects

### PR DESCRIPTION
**Pull request by archfz**
I have encountered an issue with minification of JS and the fact that the constructor.name is used to identify sources of property descriptors. Since the constructor.name is easily collideable after minification this was causing issues. Note that it was reproducing with classes in different scopes inheriting from same base class.

### CODE REVIEW

**Comment by NisStrom** [comment]
@andreas-aeschlimann 
When is this pull request going to be merged? It is quite a sincere issue, we cannot use our production build in minified version because json2Typescript fails to read the correct property mapping for our classes.

**Comment by archfz** [comment]
@NisStorm You can install with npm from the fork I have created till this gets reviewd and merge.

If you do so it would be greate if you give feedback here about the implementation so it can be merged faster. Cheers.

**Comment by NisStrom** [comment]
This implementation works well enough wit our issue.  I therefore suggest to merge this pull request.

**Comment by andreas-aeschlimann** [comment]
Sorry for the delay, but I did not have time to look into it. It will be done in the course of the next weeks.

**Comment by NisStrom** [comment]
Any news when this is going to be merged?

**Comment by andreas-aeschlimann** [comment]
Thanks for your input, I have manually implemented it and tried to fix some additional occurring issues. I hope the version 1.0.6 behaves as you expected.

**Comment by archfz** [comment]
Well thanks man. This is a good way to discourage contributions.

**Comment by andreas-aeschlimann** [comment]
I added your name to the contributors in the readme.

To be honest I didn't have the time (and know-how) to do all the merge conflicts so I copied some of the code where needed.

**Comment by archfz** [comment]
Okay. Cheers then :)

**Comment by andreas-aeschlimann** [comment]
It wasn't my intention to steal credits or anything. I didn't know better for now as this is my first public repo. I'll have more time on this project in the fall so I hope I will also have time to get into the management of pull requests.

**Pull request closed without merging**
